### ISSUE TITLE
Character filters make passwords less random

### ISSUE THREAD

**Issue by stylextv** [Quantum3566/passwordGenerator#1]
https://github.com/Quantum3566/passwordGenerator/blob/821ae0f09f02967ffde03b13577fc61431de1a6d/passwordGenerator/main.c#L27C22-L27C22

I have noticed that when generating some passwords (as can be seen in the source code linked above), you seem to never be reusing a character that is already contained within the password as well as never generating two alphabetic characters with the same case (i.e. lowercase, lowercase or uppercase, uppercase) in a row.

From a human, intuitive point of view, this may seem like you are making the password more *random* and therefore more secure, but in reality it has the opposite effect, reducing the entropy and therefore the security of your password.
It is much more secure to generate a completely random string without filtering out some patterned passwords.

An example: The generation of a 10-character password consisting of letters only without reusing a character or the direct repetition of upper/lower case (e.g. `"aWtXnLvSgU"`) would result in this many passwords being generated:

```
2 * 26 * 25 * ... * 17 = 2 * 26! / (26 - 10)! = 3.85504479E13

=> entropy = log_2(3.85504479E13) = 45.13 bits
```

Generating a completely random 10-character password (e.g. `"jcPIiPJlTx"`), on the other hand, would result in this many combinations:

```
(2 * 26) * ... * (2 * 26) = 52^10 = 1.44555106E17

=> entropy = log_2(1.44555106E17) = 57.00 bits
```

So in this case, applying these specific generation filters to the password generator would reduce the possible password space by 99.97%, which is obviously pretty bad.
Adding numeric characters would somewhat mitigate the negative effect described.

**Comment by Quantum3566** [comment]
Thank you for pointing this issue out. I will upload the updated code with the fixes. Please tell me if there are any more issues.
